### ISSUE TITLE
TypeError at startup

### ISSUE THREAD

**Issue by thelstreon** [manipuladordedados/pdiary#8]
Ubuntu 18.0.4 LTS 

When creating a new password and pressing enter, an error shows up.

TypeError: 'kdf_iter' is an invalid keyword argument for this function.

**Comment by thelstreon** [comment]
Traceback (most recent call last):
  File "/home/stratheon/.local/bin/pdiary", line 11, in <module>
    sys.exit(main())
  File "/home/stratheon/.local/lib/python3.6/site-packages/pdiary/main.py", line 37, in main
    MyApp.run()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/wgwidget.py", line 458, in edit
    self._edit_loop()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/wgwidget.py", line 474, in _edit_loop
    self.get_and_use_key_press()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/wgbutton.py", line 99, in h_toggle
    self.whenPressed()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/fmActionFormV2.py", line 10, in whenPressed
    return self.parent._on_ok()
  File "/home/stratheon/.local/lib/python3.6/site-packages/npyscreen/fmActionFormV2.py", line 51, in _on_ok
    self.editing = self.on_ok()
  File "/home/stratheon/.local/lib/python3.6/site-packages/pdiary/forms.py", line 236, in on_ok
    db = database.dbManager(self.passbox.value)
  File "/home/stratheon/.local/lib/python3.6/site-packages/pdiary/lib/database.py", line 43, in __init__
    db.create_tables([Entry])
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 3132, in create_tables
    model.create_table(**options)
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 6296, in create_table
    cls._schema.create_all(safe, **options)
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 5456, in create_all
    self.create_table(safe, **table_options)
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 5311, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 2962, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 2947, in execute_sql
    cursor = self.cursor(commit)
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 2933, in cursor
    self.connect()
  File "/home/stratheon/.local/lib/python3.6/site-packages/peewee.py", line 2891, in connect
    self._state.set_connection(self._connect())
  File "/home/stratheon/.local/lib/python3.6/site-packages/playhouse/sqlcipher_ext.py", line 71, in _connect
    conn = sqlcipher.connect(self.database, isolation_level=None, **params)
TypeError: 'kdf_iter' is an invalid keyword argument for this function

**Comment by spamegg1** [comment]
Same here.

**Comment by manipuladordedados** [comment]
Fixed.

**Comment by thelstreon** [comment]
Works fine with WSL 2.0! Thank you.
